version: '3.8'

services:
  backend:
    build: ./projeto-arquitetura-backend
    container_name: archflow-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    restart: always

  frontend:
    build: ./projeto-arquitetura-frontend
    container_name: archflow-frontend
    ports:
      - "80:80" # Mapeia porta 80 da VM para o Nginx
    depends_on:
      - backend
    restart: always
