version: '3.8'

services:
  # O servi√ßo postgres foi removido pois agora estamos utilizando o Supabase (Banco na Nuvem)
  # postgres:
  #   image: postgres:13
  #   container_name: archflow-postgres
  #   environment:
  #     POSTGRES_USER: ${DB_USERNAME}
  #     POSTGRES_PASSWORD: ${DB_PASSWORD}
  #     POSTGRES_DB: archflow_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
